### ISSUE TITLE
Expo SDK 52 - Error: Cannot read property 'regular' of undefined

### ISSUE THREAD

**Issue by h14h** [roninoss/nativewindui#19]
I got this error after attempting to upgrade my NWUI app to SDK 52, and was able to reproduce it with a minimal Expo example.

Here are my approximate reproduction steps:
1. `npx create-expo-app sdk-test --template tabs`
2. `cd sdk-test`
3. Follow the NWUI [manual installation instructions](https://nativewindui.com/installation/manual)
4. Replace `app/(tabs)/index.ts` with the "Usage Example" in Step 8
5. `npx expo prebuild --clean` followed by `npm run ios`

When the ios simulator starts up, the app crashes with `Error: Cannot read property 'regular' of undefined`.

**Comment by mrzachnugent** [comment]
Hey @h14h , I think this has to do with https://github.com/roninoss/nativewindui/blob/main/theme/index.ts where the navigation theme now has a `font` in react-navigation7. You can spread  `...DefaultTheme` and  `...DarkTheme` at the top of the light and dark objects respectively.

**Comment by h14h** [comment]
@mrzachnugent Thanks! That did it :+1:

In that case, I think this issue can be (at least partially) resolved by tweaking the `theme/color.ts` example in the manual installation instructions.

If I get around to making a PR for the issues I noted in #20, I'll address this there too.
