### ISSUE TITLE
DropdownMenu & ContextMenu using non-existent Ref

### ISSUE THREAD

**Issue by h14h** [roninoss/nativewindui#21]
A freshly installed `DropdownMenu` has the following TS error:

```
@rn-primitives/dropdown-menu/dist/index"' has no exported member 'DropdownMenuTriggerRef'
```

The `@rn-primitives/dropdown-menu` has version `^1.1.0`, and `DropdownMenu` was installed via the CLI:

```
npx nwui-cli@latest add dropdown-menu
```

Looks like it should be referencing `DropdownMenu.TriggerRef` instead of `DropdownMenu.DropdownMenuTriggerRef`:

```diff
-    const triggerRef = React.useRef<DropdownMenuPrimitive.DropdownMenuTriggerRef>(null);
+    const triggerRef = React.useRef<DropdownMenuPrimitive.TriggerRef>(null);
```

The above is also true for `ContextMenu`.

Happy to put up a PR to fix this, I'm just not sure where the CLI pulls its code from.

**Comment by mrzachnugent** [comment]
@h14h Thanks for contributing! It has been fixed.
